[build-system]
requires = ["wheel", "setuptools", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "qulacs"
description = "Quantum circuit simulator for research"
authors = [
    { name = "QunaSys", email = "qulacs@qunasys.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
dependencies = []
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Topic :: Communications :: Email"
]

[tool.setuptools.dynamic]
version = {attr = "qulacs._version.__version__"}

[tool.setuptools_scm]
write_to = "pysrc/qulacs/_version.py"

[project.urls]
homepage = "http://www.qulacs.org"

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "openfermion",
    "mypy",
    "pybind11-stubgen"
]

test = [
    "openfermion"
]

ci = [
    "openfermion",
    "mypy",
    "pybind11-stubgen"
]

doc = [
    "sphinx == 4.5.0",
    "sphinx-rtd-theme == 1.0.*",
    "breathe == 4.33.*",
    "exhale == 0.3.*",
    "nbsphinx == 0.8.*",
    "myst-parser == 0.18.*",
    "sphinx-copybutton == 0.5.*",
    "ipykernel == 6.17.*",
    "sphinx-autoapi == 2.0.*"
]

[tool.setuptools]
include-package-data = true
zip-safe = false
